// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obdkyezuyakyiqgfgfcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZGt5ZXp1eWFreWlxZ2ZnZmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQ2ODQsImV4cCI6MjA2NTU2MDY4NH0.vXBmJ-vWkbNUHIzXy_q9O_4IBJWK3aV72K5Tx4yKOik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);